### ISSUE TITLE
[FEAT] Make it easier to define errors in IPipelineMessage

### ISSUE THREAD

**Issue by azeredogab** [kallebelins/mvp24hours-dotnet#2]
## Context:

While using the pipelines functionality in a project, when I got an error in a part of a step, I needed to inform the pipeline that an error had occurred and also create a custom error message with details of the error, so I did it as follows:

```
public override void Execute(IPipelineMessage input)
{
...
input.Messages.Add("my custom error message".ToMessageResult(MessageType.Error));
```

## Suggestion:

My suggestion is to create a method to shorten this line a bit, making the code a bit leaner, as follows:

```
input.AddError("minha mensagem de erro");
```

@kallebelins what do you think about it?

**Comment by kallebelins** [comment]
It must be kept isolated to maintain the correct reference to the Pipe and Filters Standard.
- Pipeline is a tube through which a package passes through.
- Operations/Filters are applied while the packet travels through the pipe.
- Message is the package that travels through the Pipeline and may have attachments.

**Comment by azeredogab** [comment]
@kallebelins gotcha. 

As we discussed in private, that new method `AddError` will be just like a "syntax sugar" to do something that is already done now (the first example). 

I'll sumbit a PR to add that.
